pub mod clawhub;
pub mod compat;
pub mod config;
pub mod config_watcher;
pub mod error;
pub mod hooks;
pub mod identity;
pub mod persistence;
pub mod providers;
pub mod sanitizer;
pub mod scanner;
pub mod secrets;
pub mod skill_loader;
pub mod skill_parser;
pub mod skills;
pub mod tool_resolver;
pub mod types;

pub use clawhub::{ClawHubClient, ClawHubSearchResult, ClawHubSkillMeta, InstalledSkillInfo, SkillInstaller, SkillSource};
pub use config::McclawdConfig;
pub use error::{McclawdError, Result};
pub use sanitizer::sanitize_prompt;
pub use scanner::{ScanResult, ScanStatus, ScanIssue};
pub use skill_loader::SkillLoader;
pub use skills::{LoadedSkill, SandboxConfig};
pub use tool_resolver::{ResolvedToolSet, ToolResolver};
pub use types::{AgentId, SessionId, TaskId};
